# Generated by Django 5.1.4 on 2024-12-14 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='Name of the Condition', default='', max_length=200)),
                ('description', models.TextField(db_comment='Description pulled from Archives of Nethys', default='')),
                ('has_value', models.BooleanField(db_comment='Whether the condition has a value', default=False)),
                ('ac_mod', models.IntegerField(default=0)),
                ('hp_mod', models.IntegerField(default=0)),
                ('will_mod', models.IntegerField(default=0)),
                ('fortitude_mod', models.IntegerField(default=0)),
                ('reflex_mod', models.IntegerField(default=0)),
                ('perception_mod', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InitEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='Name of the player/NPC', default='', max_length=200)),
                ('aon_link', models.CharField(db_comment='Archives of Nethys Link', default='', max_length=200)),
                ('skills', models.CharField(db_comment='List of Skills not including perception', default='', max_length=200)),
                ('ac', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('will_save', models.IntegerField(default=0)),
                ('fortitude_save', models.IntegerField(default=0)),
                ('reflex_save', models.IntegerField(default=0)),
                ('initiative', models.IntegerField(default=0)),
                ('perception', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField(db_comment='Condition Value', default=0)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative.conditionoption')),
                ('affected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative.initentry')),
            ],
        ),
    ]
