# Generated by Django 3.2.6 on 2022-05-27 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('article', models.TextField(default='')),
                ('month', models.CharField(choices=[('Genysi', 'Birth'), ('Tixyl', 'Melting'), ('Rysumas', 'Roots'), ('Anthys', 'Bloom'), ('Perigree', 'Apex'), ('Ekarpo', 'Fruiting'), ('Ludere', 'Play'), ('Therismo', 'Reap'), ('Chima', 'Death'), ('Skotad', 'Darkness'), ('Apogee', 'Bottom'), ('Pagos', 'Ice')], max_length=20)),
                ('day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
            ],
        ),
    ]
