# Generated by Django 3.2.6 on 2022-05-27 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='era',
            field=models.CharField(choices=[('Uniting', 'First Age'), ('Trade', 'Second Age'), ('Expansion', 'Third Age'), ('Magic', 'Fourth Age'), ('Wealth', 'Fifth Age'), ('War', 'Sixth Age'), ('Golden', 'Seventh Age'), ('Calamity', 'Eight Age'), ('Restoration', 'Ninth Age'), ('Industry', 'Tenth Age'), ('Modern', 'Eleventh Age'), ('Technology', 'Twelfth Age')], default='War', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='month',
            field=models.CharField(choices=[('Genysi', 'Birth'), ('Tixyl', 'Melting'), ('Rysumas', 'Roots'), ('Anthys', 'Bloom'), ('Perigree', 'Apex'), ('Ekarpo', 'Fruiting'), ('Ludere', 'Play'), ('Therismo', 'Reap'), ('Chima', 'Death'), ('Skotad', 'Darkness'), ('Apogee', 'Bottom'), ('Pagos', 'Ice')], default='Genysi', max_length=20),
        ),
    ]
