# Generated by Django 3.2.6 on 2022-07-25 15:02

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220527_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='era',
            field=models.CharField(choices=[('Uniting', 'First_Age'), ('Trade', 'Second_Age'), ('Expansion', 'Third_Age'), ('Magic', 'Fourth_Age'), ('Wealth', 'Fifth_Age'), ('War', 'Sixth_Age'), ('Golden', 'Seventh_Age'), ('Calamity', 'Eight_Age'), ('Restoration', 'Ninth_Age'), ('Industry', 'Tenth_Age'), ('Modern', 'Eleventh_Age'), ('Technology', 'Twelfth_Age')], default=news.models.Era['Sixth_Age'], help_text='<p>First_Age = Uniting</p><p>Second_Age = Trade</p><p>Third_Age = Expansion</p><p>Fourth_Age = Magic</p><p>Fifth_Age = Wealth</p><p>Sixth_Age = War</p><p>Seventh_Age = Golden</p><p>Eight_Age = Calamity</p><p>Ninth_Age = Restoration</p><p>Tenth_Age = Industry</p><p>Eleventh_Age = Modern</p><p>Twelfth_Age = Technology</p>', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='month',
            field=models.CharField(choices=[('Genysi', 'Birth'), ('Tixyl', 'Melting'), ('Rysumas', 'Roots'), ('Anthys', 'Bloom'), ('Perigree', 'Apex'), ('Ekarpo', 'Fruiting'), ('Ludere', 'Play'), ('Therismo', 'Reap'), ('Chima', 'Death'), ('Skotad', 'Darkness'), ('Apogee', 'Bottom'), ('Pagos', 'Ice')], default=news.models.Month['Birth'], help_text='<p>Birth = Genysi</p><p>Melting = Tixyl</p><p>Roots = Rysumas</p><p>Bloom = Anthys</p><p>Apex = Perigree</p><p>Fruiting = Ekarpo</p><p>Play = Ludere</p><p>Reap = Therismo</p><p>Death = Chima</p><p>Darkness = Skotad</p><p>Bottom = Apogee</p><p>Ice = Pagos</p>', max_length=20),
        ),
    ]
