# Generated by Django 3.2 on 2021-04-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('government', models.TextField(default='')),
                ('governing_body', models.CharField(default='', max_length=200)),
                ('economy', models.TextField(default='')),
                ('population', models.BigIntegerField(default=0)),
                ('x_coord_max', models.IntegerField(default=0)),
                ('y_coord_max', models.IntegerField(default=0)),
                ('x_coord_min', models.IntegerField(default=0)),
                ('y_coord_min', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.town')),
            ],
        ),
    ]
