# Generated by Django 3.2 on 2021-04-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='leader',
        ),
        migrations.AddField(
            model_name='town',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.person'),
        ),
    ]
