# Generated by Django 3.2 on 2021-04-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_town_generator_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorshop',
            name='quest_shop_inf',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='generatorshop',
            name='quest_shop_lhi',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='generatorshop',
            name='quest_shop_llo',
            field=models.IntegerField(default=5),
        ),
    ]
