# Generated by Django 3.2 on 2021-04-25 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20210424_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.person'),
        ),
    ]
