# Generated by Django 3.2 on 2021-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='admin_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='admin_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
