# Generated by Django 3.2 on 2021-06-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_person_img_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img_source',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
