# Generated by Django 3.2.6 on 2022-06-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_person_img_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='magic_phrase',
            field=models.CharField(default='', max_length=200),
        ),
    ]
