# Generated by Django 3.2.6 on 2022-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_town_magic_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='img_source',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
