# Generated by Django 5.1.4 on 2024-12-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_alter_choice_available_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='generator_settings',
        ),
        migrations.RemoveField(
            model_name='town',
            name='leader',
        ),
        migrations.DeleteModel(
            name='GeneratorShop',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
