from django.urls import path
from . import views

urlpatterns = [
    path('', views.api, name='api'),
    path('npc/', views.npc, name='npc'),
    path('npc/json/', views.npc_json, name='npc_json'),
    path('pc/', views.pc, name='pc'),
    path('pc/json/', views.pc_json, name='pc_json'),

    path('beast/', views.beast, name='beast'),
    path('beast/json/', views.beast_json, name='beast_json'),
    path('beast/5e/', views.beast_5e, name='beast_5e'),
    path('beast/5e/json/', views.beast_5e_json, name='beast_5e_json'),
    path('beast/pf1/', views.beast_pf1, name='beast_pf1'),
    path('beast/pf1/json/', views.beast_pf1_json, name='beast_pf1_json'),

    path('treasure/pf1/', views.treasure_pf1, name='treasure_pf1'),
    path('treasure/pf1/json/', views.treasure_pf1_json, name='treasure_pf1_json'),
    path('treasure/pf1/<int:cr>/', views.treasure_pf1_cr, name='treasure_pf1'),
    path('treasure/pf1/<int:cr>/json/', views.treasure_pf1_cr_json, name='treasure_pf1_json'),

    path('store/weapon/', views.store_weapon, name='store_weapon'),
    path('store/weapon/json/', views.store_weapon_json, name='store_weapon_json'),
    path('store/armor/', views.store_armor, name='store_armor'),
    path('store/armor/json/', views.store_armor_json, name='store_armor_json'),
    path('store/firearm/', views.store_firearm, name='store_firearm'),
    path('store/firearm/json/', views.store_firearm_json, name='store_firearm_json'),
    path('store/book/', views.store_book, name='store_book'),
    path('store/book/json/', views.store_book_json, name='store_book_json'),
    path('store/enchanter/', views.store_enchanter, name='store_enchanter'),
    path('store/enchanter/json/', views.store_enchanter_json, name='store_enchanter_json'),
    path('store/scroll/', views.store_scroll, name='store_scroll'),
    path('store/scroll/json/', views.store_scroll_json, name='store_scroll_json'),
    path('store/potion/', views.store_potion, name='store_potion'),
    path('store/potion/json/', views.store_potion_json, name='store_potion_json'),
    path('store/jewel/', views.store_jewel, name='store_jewel'),
    path('store/jewel/json/', views.store_jewel_json, name='store_jewel_json'),
    path('store/general/', views.store_general, name='store_general'),
    path('store/general/json/', views.store_general_json, name='store_general_json'),
    path('store/food/', views.store_food, name='store_food'),
    path('store/food/json/', views.store_food_json, name='store_food_json'),
    path('store/inn/', views.store_inn, name='store_inn'),
    path('store/inn/json/', views.store_inn_json, name='store_inn_json'),
    path('store/variety/', views.store_variety, name='store_variety'),
    path('store/variety/json/', views.store_variety_json, name='store_variety_json'),

    path('item/weapon/', views.item_weapon, name='item_weapon'),
    path('item/weapon/json/', views.item_weapon_json, name='item_weapon_json'),
    path('item/weapon/<int:r>/', views.item_weapon_r, name='item_weapon_r'),
    path('item/weapon/<int:r>/json/', views.item_weapon_r_json, name='item_weapon_r_json'),
    path('item/armor/', views.item_armor, name='item_armor'),
    path('item/armor/json/', views.item_armor_json, name='item_armor_json'),
    path('item/armor/<int:r>/', views.item_armor_r, name='item_armor_r'),
    path('item/armor/<int:r>/json/', views.item_armor_r_json, name='item_armor_r_json'),
    path('item/firearm/', views.item_firearm, name='item_firearm'),
    path('item/firearm/json/', views.item_firearm_json, name='item_firearm_json'),
    path('item/firearm/<int:r>/', views.item_firearm_r, name='item_firearm_r'),
    path('item/firearm/<int:r>/json/', views.item_firearm_r_json, name='item_firearm_r_json'),
    path('item/scroll/', views.item_scroll, name='item_scroll'),
    path('item/scroll/json/', views.item_scroll_json, name='item_scroll_json'),
    path('item/scroll/<int:r>/', views.item_scroll_r, name='item_scroll_r'),
    path('item/scroll/<int:r>/json/', views.item_scroll_r_json, name='item_scroll_r_json'),
]
